import org.junit.Test;

public class TestBw {
    @Test
    public void testEncode(){
        assert BurrowsWheeler.encode("AASDFADGFSAFDGSDFGSDFHGHDFGHKLSDFJKDFJLGHKDHFGHLASDFHASDLKFHAKLDSFHAKLSDHFKLADHFKLASDHFLASHFLAKSDHFLAKSHDFKLAKSHDF").equals("FFLSHHLLLALLHLHSHSSSSKHAFKSASSSLDDADHDKSDDDDHDHHHHGDHLFFDFFFFSGSDDDSDDFGGGFFJHLFFFAHAAAAKFKFHKFKJDKKFAGAGLLKAADKKA");
    }

    @Test
    public void testDecode(){
        assert BurrowsWheeler.decode(0,"FFLSHHLLLALLHLHSHSSSSKHAFKSASSSLDDADHDKSDDDDHDHHHHGDHLFFDFFFFSGSDDDSDDFGGGFFJHLFFFAHAAAAKFKFHKFKJDKKFAGAGLLKAADKKA").equals("AASDFADGFSAFDGSDFGSDFHGHDFGHKLSDFJKDFJLGHKDHFGHLASDFHASDLKFHAKLDSFHAKLSDHFKLADHFKLASDHFLASHFLAKSDHFLAKSHDFKLAKSHDF");
    }
}
